from lesson_guard import predicates as p


def test_line_ending_styles():
    assert p.line_ending_styles("a\r\nb\r\n") == {"crlf"}
    assert p.line_ending_styles("a\nb\n") == {"lf"}
    assert p.line_ending_styles("a\r\nb\n") == {"crlf", "lf"}
    assert p.line_ending_styles("a\rb") == {"cr"}
    assert p.line_ending_styles("no break") == set()


def test_mixed_line_endings():
    assert p.mixed_line_endings("a\r\nb\nc\r\n")
    assert not p.mixed_line_endings("a\r\nb\r\n")
    assert not p.mixed_line_endings("a\nb\n")
    assert not p.mixed_line_endings("")


def test_line_endings_changed():
    assert p.line_endings_changed("a\r\nb\n", "a\nb\n")
    assert p.line_endings_changed("a\r\nb\r\n", "a\nb\n")
    assert not p.line_endings_changed("a\r\nb\n", "a\r\nX\n")
    assert not p.line_endings_changed(None, "a\n")
    assert not p.line_endings_changed("a\r\n", None)
    assert not p.line_endings_changed("a\r\n", "single line")


def test_utf8_double_encoded_detects_mojibake():
    good = "Gr\u00fcezi, fa\u00e7ade, 5 \u20ac, \u00e9t\u00e9, \u00df"
    broken = good.encode("utf-8").decode("cp1252", errors="replace")
    assert p.utf8_double_encoded(broken)
    assert not p.utf8_double_encoded(good)
    # Right single quote double-encoded via cp1252.
    assert p.utf8_double_encoded("It\u00e2\u20ac\u2122s")
    # Latin-1 route (no cp1252 specials).
    assert p.utf8_double_encoded("\u00c3\u00a4")


def test_utf8_double_encoded_ignores_clean_text():
    for text in ["plain ascii", "\u00c4rger \u00fcber \u00d6l", "\u00a9 2026", "\u65e5\u672c\u8a9e", "caf\u00e9 au lait", ""]:
        assert not p.utf8_double_encoded(text), text


def test_secret_like_provider_formats():
    # Built at runtime so no key-shaped literal lives in the repository.
    samples = [
        "sk-" + "ant-" + "a1B2c3D4e5F6g7H8i9J0k1L2m3",
        "AKIA" + "Q" * 16,
        "ghp_" + "a1" * 18,
        "xoxb-" + "1234567890-abcdef",
        "-----BEGIN " + "RSA PRIVATE KEY-----",
    ]
    for sample in samples:
        assert p.contains_secret_like(f"value = {sample}"), sample


def test_secret_like_assignments():
    assert p.contains_secret_like('api_key = "q8Zr2Lx9Wv4Tn7Kp3Hs6Jd1Fm5Bc0Yg"')
    assert p.contains_secret_like("TOKEN: Zx81Qw7Er6Ty5Ui4Op3As2Df")
    assert p.contains_secret_like('{"db_password": "Pq9Lm2Xz7Rt4Vb6Nc1Ks8Hd"}')


def test_secret_like_ignores_placeholders_and_env_references():
    for text in [
        'api_key = "your-api-key-here"',
        'API_KEY = os.environ["API_KEY"]',
        "token = process.env.TOKEN",
        "password = aaaaaaaaaaaaaaaaaaaa",
        "secret = abcdefghijklmnopqrstuvwxyz",
        "the token expires after 30 minutes",
        "",
    ]:
        assert not p.contains_secret_like(text), text


def test_generated_marker():
    assert p.file_is_generated_marker("# Code generated by gen.py. DO NOT EDIT.\nx = 1\n")
    assert p.file_is_generated_marker("// @generated\nexport {}\n")
    assert p.file_is_generated_marker("/* This file is automatically generated */\n")
    assert p.file_is_generated_marker("# Auto-generated from schema.yaml\n")
    assert not p.file_is_generated_marker("x = 1\n# generator docs are in docs/\n")
    # Markers far below the head do not count.
    assert not p.file_is_generated_marker("x = 1\n" * 40 + "# DO NOT EDIT\n")
